name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Кеширование NuGet пакетов
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Настройка .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Сборка решения
        run: dotnet build Atune.sln --no-restore --configuration Release

      - name: Запуск тестов с покрытием кода
        run: dotnet test Atune.sln --no-restore --configuration Release /p:CollectCoverage=true /p:CoverletOutput=coverage/ /p:CoverletOutputFormat=opencover --verbosity normal

      - name: Загрузка отчёта покрытия
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  debug-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Настройка .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Компиляция и запуск linux-x64 Debug
        run: dotnet run --project Atune.Desktop/Atune.Desktop.csproj --configuration Debug --runtime linux-x64 